# Generated by Django 4.0.6 on 2022-08-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_img',
            new_name='profileimg',
        ),
    ]
